### ISSUE TITLE
4.5.1 TimeIn - needs informational note or edit

### ISSUE THREAD

**Issue by SteveLLamb** [SMPTE/rp428-22#5]
Note needs to be added re: 4 sec for first subtitle event, to apply _only_ if reel length is more than 4 secs in length. Need to figure out wording for note and/or adjusting current text to allow for this.

**Comment by SteveLLamb** [comment]
Commenter and DG approves update per DG meeting 20220328

**Comment by MartinaBerger** [comment]
Is it possible to make an updated PCD version including this revision available for reviewing?
Thanks!

**Comment by SteveLLamb** [comment]
> Is it possible to make an updated PCD version including this revision available for reviewing? Thanks!

@MartinaBerger Yes, the document is undergoing pre-FCD ballot review in 21DC for 2 weeks. Once that completes there will be a PCD2 PDF updated for this repo while the FCD ballot and remaining SMPTE process continues. When the document is finally published, this repo will revert to an issue tracker and the PCD/PCD2 will be removed.
