### ISSUE TITLE
A.1 LoadFont ID - Use neutral identifier

### ISSUE THREAD

**Issue by jack-watts** [SMPTE/rp428-22#6]
Use the neutral identifier of "MinRefFont" over "Arial" as a FontID in the informative example in Annex A1, as it is misleading in the sense that even though it is just an arbitrary identifier, readers could wrongfully conclude it to be referencing a valid font file. Such examples bear the risk of being interpreted as normative if not read carefully.

**Comment by SteveLLamb** [comment]
Addressed in "redlinefromPCD1" version 20220328 https://smpte.sharepoint.com/:w:/s/21DCAHGStereoSubtitling/ESlXQ6VIiJtHrr0O609Fe5IBWRYS4BoTUWPhFH4dOn0uZw?e=dl1e4a

**Comment by SteveLLamb** [comment]
Commenter and DG approves update per DG meeting 20220328
