### ISSUE TITLE
Incorrect identification of document type

### ISSUE THREAD

**Issue by jhursty** [SMPTE/rp428-22#7]
Maybe overly pedantic, but re. A.1 and A.2, the text "valid instance of the SubtitleReel schema" would only apply to an XML document that is a schema. In this case the XML document is not a instance of `schema`, it is an instance of `SubtitleReel` (i.e., the top-level element is `SubtitleReel`, not `schema`.)

I propose the replacement text "valid instance of a SubtitleReel document conforming to schema http://www.smpte-ra.org/schemas/428-7/2014/DCST", or "valid instance of a SubtitleReel document conforming to ST 428-7"

**Comment by SteveLLamb** [comment]
Addressed in "redlinefromPCD1" version 20220328 https://smpte.sharepoint.com/:w:/s/21DCAHGStereoSubtitling/ESlXQ6VIiJtHrr0O609Fe5IBWRYS4BoTUWPhFH4dOn0uZw?e=dl1e4a

**Comment by SteveLLamb** [comment]
DG approves update per DG meeting 20220328, will work with commenter offline to mark issue resolved.
