### ISSUE TITLE
4.7 Image

### ISSUE THREAD

**Issue by RichardHarkin** [SMPTE/rp428-22#8]
Transparent is defined by Alpha = 00 ?

**Comment by jack-watts** [comment]
If you are referring to the alpha channel representation in the RGBA Color Model, yes, the word transparent is synonymous with the alpha channel being 0 to indicate transparent alpha.

**Comment by SteveLLamb** [comment]
DG approves no update per DG meeting 20220328, will work with commenter offline to mark issue resolved.

**Comment by SteveLLamb** [comment]
Spoke with @RichardHarkin offline, and he accepts this (2022-03-29).
